#!/bin/bash
rm -rf dashboard.out dashboard.err dashboard.log
panel serve --prefix /FOCICruise --disable-index-redirect --port 8947 --allow-websocket-origin haboob.local:8947 --log-file dashboard.log holoviz_erddap_CTDMapper.ipynb > dashboard.out 2>dashboard.err
